version: '3.8'

services:
  thai_summarizer:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    container_name: thai_summarizer_app
    volumes:
      - ./uploads:/app/uploads